version: '3.9'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:15-alpine3.18
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - .:/logs:/var/log
    env_file:
      - ".env.dev.db"
    ports:
      - "5431:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d api_stocks" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  web:
    depends_on:
      - db
    build: .
    command: >
      bash -c "
        sleep 3 &&
        python manage.py collectstatic --no-input &&
        python manage.py makemigrations --noinput &&
        python manage.py migrate --noinput &&
        gunicorn orders.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/usr/app/diplom
      - static_volume:/usr/app/diplom/static
      - media_volume:/usr/app/diplom/media
    ports:
      - "8000:8000"
    expose:
      - 8000
    env_file:
      - ".env.dev"

#python manage.py migrate --noinput &&

  nginx:
    depends_on:
      - web
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - static_volume:/usr/app/diplom/static
      - media_volume:/usr/app/diplom/media


#python manage.py runserver 0.0.0.0:8000